name: notify

on:
  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Telegram Notify
        uses: appleboy/telegram-action@0.0.7
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          format: markdown
          message: |
            [${{ github.event.comment.user.login }} Comment on #${{ github.event.issue.number }} ${{ github.event.issue.title }}](${{ github.event.comment.html_url }})
            ${{ github.event.comment.body }}
